#!/usr/bin/env python3
"""
Sonnet-Gate v3 — Generated File Archiver
Dual hook: PreToolUse (archive TRƯỚC khi bị ghi đè) + PostToolUse (archive SAU khi ghi xong).

Timeline của 1 Write event:
  PreToolUse  → copy file CŨ (trước khi Claude ghi đè)  → archive/name-TIMESTAMP-pre.md
  [Claude writes file]
  PostToolUse → copy file MỚI (sau khi Claude ghi xong) → archive/name-TIMESTAMP-post.md

Tại sao cả hai?
  - Pre:  bảo toàn version cũ, không bao giờ mất dữ liệu dù Claude crash giữa chừng
  - Post: lưu lại version mới để diff/audit sau này

Watched files đọc từ complexity-config.json (key "watched_files").
Fallback mặc định: context-snapshot.md, execution-plan.md, execution-report.md

Tự động update .gitignore của project nếu chưa có entry cho .claude/archive/.

Setup:
  chmod +x ~/.claude/hooks/archive-generated-files.py

Đăng ký trong ~/.claude/settings.json:
  {
    "hooks": {
      "PreToolUse": [{
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [{"type": "command",
                   "command": "python3 \\"$HOME/.claude/hooks/archive-generated-files.py\\" pre",
                   "timeout": 5}]
      }],
      "PostToolUse": [{
        "matcher": "Write|Edit|MultiEdit",
        "hooks": [{"type": "command",
                   "command": "python3 \\"$HOME/.claude/hooks/archive-generated-files.py\\" post",
                   "timeout": 5}]
      }]
    }
  }

Test thủ công:
  # Test Pre (archive file cũ trước khi ghi)
  echo '{"tool_name":"Write","tool_input":{"file_path":"/your/project/.claude/execution-plan.md"}}' \\
    | CLAUDE_PROJECT_DIR="/your/project" python3 ~/.claude/hooks/archive-generated-files.py pre

  # Test Post (archive file mới sau khi ghi)
  echo '{"tool_name":"Write","tool_input":{"file_path":"/your/project/.claude/execution-plan.md"}}' \\
    | CLAUDE_PROJECT_DIR="/your/project" python3 ~/.claude/hooks/archive-generated-files.py post
"""
import sys
import json
import os
import shutil
from datetime import datetime
from pathlib import Path

# ── Paths & defaults ───────────────────────────────────────────────────────────
CONFIG_PATH = Path.home() / ".claude" / "hooks" / "complexity-config.json"

DEFAULT_WATCHED = {
    "context-snapshot.md",
    "execution-plan.md",
    "execution-report.md",
}

DEFAULT_GITIGNORE_ENTRIES = [
    ".claude/archive/",
    ".claude/logs/",
]

# ── Config loader ──────────────────────────────────────────────────────────────
def load_watched_files() -> set:
    if CONFIG_PATH.exists():
        try:
            with open(CONFIG_PATH, encoding="utf-8") as f:
                cfg = json.load(f)
            files = cfg.get("watched_files")
            if isinstance(files, list) and files:
                return set(files)
        except Exception:
            pass
    return DEFAULT_WATCHED

def load_gitignore_entries() -> list:
    if CONFIG_PATH.exists():
        try:
            with open(CONFIG_PATH, encoding="utf-8") as f:
                cfg = json.load(f)
            entries = cfg.get("gitignore_entries")
            if isinstance(entries, list):
                return entries
        except Exception:
            pass
    return DEFAULT_GITIGNORE_ENTRIES

# ── Project dir ────────────────────────────────────────────────────────────────
def get_project_dir() -> Path:
    return Path(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())

# ── Archiver ───────────────────────────────────────────────────────────────────
def archive_file(src: Path, archive_dir: Path, phase: str) -> str | None:
    """
    Copy src vào archive_dir với suffix timestamp + phase label.
    phase: "pre" | "post"
    Returns archive path string hoặc None nếu src không tồn tại.
    """
    if not src.exists():
        return None

    ts           = datetime.now().strftime("%Y%m%d-%H%M%S")
    archive_name = f"{src.stem}-{ts}-{phase}{src.suffix}"
    archive_path = archive_dir / archive_name

    archive_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, archive_path)
    return str(archive_path)

# ── .gitignore updater ─────────────────────────────────────────────────────────
def ensure_gitignore(project_dir: Path):
    """
    Thêm entries vào .gitignore nếu chưa có.
    Chỉ chạy 1 lần per project (check trước khi write).
    """
    try:
        gitignore_path = project_dir / ".gitignore"
        entries_needed = load_gitignore_entries()

        existing_text = gitignore_path.read_text(encoding="utf-8") if gitignore_path.exists() else ""
        existing_lines = set(existing_text.splitlines())

        missing = [e for e in entries_needed if e not in existing_lines]
        if not missing:
            return  # nothing to do

        block = "\n# Sonnet-Gate — auto-generated by archive hook\n" + "\n".join(missing) + "\n"
        with open(gitignore_path, "a", encoding="utf-8") as f:
            f.write(block)

        print(f"[archive] .gitignore updated: added {missing}", file=sys.stderr)
    except Exception:
        pass  # gitignore update failure không cản luồng chính

# ── Main ───────────────────────────────────────────────────────────────────────
def main():
    # phase argument: "pre" | "post" (passed as argv[1])
    phase = sys.argv[1] if len(sys.argv) > 1 else "post"
    if phase not in ("pre", "post"):
        phase = "post"

    try:
        data       = json.loads(sys.stdin.read())
        tool_name  = data.get("tool_name", "")
        tool_input = data.get("tool_input", {})

        # Chỉ xử lý Write và Edit tools
        if tool_name not in ("Write", "Edit", "MultiEdit"):
            sys.exit(0)

        # Lấy file path từ tool input (Write dùng "file_path", Edit dùng "path")
        file_path = (
            tool_input.get("file_path")
            or tool_input.get("path")
            or ""
        )
        if not file_path:
            sys.exit(0)

        written_path = Path(file_path)
        filename     = written_path.name

        # Chỉ archive nếu file nằm trong watched list
        watched = load_watched_files()
        if filename not in watched:
            sys.exit(0)

        project_dir = get_project_dir()
        archive_dir = project_dir / ".claude" / "archive"

        # Pre phase: archive phiên bản CŨ (file tồn tại trước khi Claude ghi)
        # Post phase: archive phiên bản MỚI (file sau khi Claude ghi xong)
        # Cả hai đều dùng cùng logic, chỉ khác phase label trong tên file
        archived = archive_file(written_path, archive_dir, phase)

        if archived:
            label = "pre-archive (old)" if phase == "pre" else "post-archive (new)"
            print(
                f"[archive/{label}] {filename} → {Path(archived).name}",
                file=sys.stderr,
            )
        elif phase == "pre":
            # File chưa tồn tại (lần đầu tạo) — không phải lỗi
            print(
                f"[archive/pre] {filename} not found (first write, skipping pre-archive)",
                file=sys.stderr,
            )

        # Đảm bảo .gitignore đã có entries phù hợp
        # Chỉ chạy 1 lần ở post phase để tránh double-check
        if phase == "post":
            ensure_gitignore(project_dir)

        sys.exit(0)

    except json.JSONDecodeError:
        print("sonnet-gate archiver: invalid JSON input", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"sonnet-gate archiver error: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
